- name: copying the application 
  copy:
    src: artifact.tar.gz
    dest: ~/ 

- name: Extract the app 
  unarchive:
    src: ~/artifact.tar.gz
    dest: ~/

- name: install node modules
  shell:
    cd ~/backend
    npm i

- name: starting the app
  shell:
    cd ~/backend/dist
    pm2 stop default
    pm2 start main.js
