- name: copying the application 
  copy:
    src: ~/artifact.tar.gz
    dest: ~/artifact.tar.gz 

- name: making a dir
  shell:
    mkdir ~/backend

- name: Extract the app 
  unarchive:
    src: ~/artifact.tar.gz
    dest: ~/backend

- name: install node modules
  shell:
    cd ~/backend
    npm i

- name: starting the app
  shell:
    pm2 stop default
    pm2 start npm -- start
