- name: making a dir for backend
  file:
    path: ~/backend
    state: directory

- name: get extracted artifact into backend
  unarchive:
     src: ~/project/artifact.tar.gz
     dest: ~/backend

- name: Installing  node modules
  command: npm install
  args:
    chdir: ~/backend

- name: starting node server
  command: pm2 start npm -- start
  args:
    chdir: ~/backend


