version: 2.1

jobs:
  deploy-frontend:
    docker:
     - image: nikolaik/python-nodejs:python3.7-nodejs14
    steps:
    - checkout
    - run: 
        name: deploy frontend objects
        command: |
          cd frontend
          npm install
          npm run build
          tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
          aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive

workflows:
  default:
    jobs:
      - deploy-frontend 
