version: 2.1

jobs:
  deploy-frontend:
    docker:
     - image: nikolaik/python-nodejs:python3.7-nodejs14
    steps:
    - checkout
    - run: |
       apt-get update -y
       apt-get install -y tar gzip curl
       pip install awscli
    - run: 
        name: get backend URL
        command: |
           export BACKEND_IP=$(aws ec2 describe-instances --query "Reservations[*].Instances[*].PublicIpAddress" --filters  "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}") 
           export API_URL="http://${BACKEND_IP}:3030" 
           echo "API_URL = ${API_URL}" 
           echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env 
           cat frontend/.env
    - run: deploy frontend objects
      command: |
         cd frontend
         npm install
         npm run build
         tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
         aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive

workflows:
  default:
    jobs:
      - deploy-frontend 
