version: 2.1
jobs:
  configure-infrastructure:
    docker:
      - image: python:3.8-slim
    steps:
    - checkout
    - add_ssh_keys:
        fingerprints:
          - "5c:81:b9:e8:60:b2:22:32:12:69:7c:fe:05:b3:da:9e"
    - run:
        name: Setup dependencies
        command: |
           apt -y update
           apt -y install tar gzip openssh-client
           pip install ansible awscli 
    - attach_workspace:
         at: ~/project
    - run:
        name: run ansible playbook
        command: |
          cd .circleci/ansible
          ansible-playbook -i inventory.txt configure-server.yml

workflows:
  default:
    jobs:
      - configure-infrastructure
