version: 2.1

jobs:
  deploy-backend:
    docker:
     - image: python:3.8-slim
    steps:
    - checkout
    - restore_cache:
        keys: [backend-cache]
    - add_ssh_keys:
        fingerprints: [ "5c:81:b9:e8:60:b2:22:32:12:69:7c:fe:05:b3:da:9e" ]
    - run: 
       name: installing depndencies
       command: |
         apt -y update
         apt -y install tar gzip nodejs npm curl
    - run:
       name: install ansible and awscli
       command: |
         pip install ansible awscli
    - attach_workspace:
         at: ~/
    - run:
       name: deploying backend
       command: |
         cd backend
         npm i
         npm run build
         cd ..
         # Zip the directory
         tar -C backend -czvf artifact.tar.gz .
         mv artifact.tar.gz .circleci/ansible/roles/deploy/files
         cd .circleci/ansible
         echo "Contents  of the inventory.txt file is -------"
         cat inventory.txt
         export ANSIBLE_HOST_KEY_CHECKING=False
         ansible-playbook -i inventory.txt deploy-backend.yml
    
workflows:
  default:
    jobs:
      - deploy-backend
