version: 2.1

jobs:
  smoke-test:
    docker:
      - image: amazon/aws-cli
    steps:
    - checkout
    - run:
        name: install some dependencies
        command: |
           yum -y update
           yum -y upgrade
           yum -y install curl
    - run: 
        name: Backend smoke test
        command: |
           export API_URL="http://54.89.190.166:3030"
           echo "${API_URL}"
           if curl "${API_URL}/api/status" | grep "ok"
           then
              return 0
           else
              return 1
           fi
    - run:
        name: Frontend smoke test
        command: |
             URL="http://udapeople-3c80c12.s3-website-us-east-1.amazonaws.com/#/employees"
             echo ${URL}
             if curl -s ${URL} | grep "Welcome"
             then
                return 1
             else
                return 1
             fi
workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires:
            - build-frontend
      - test-backend:
          requires:
            - build-backend
      - scan-frontend:
          requires:
            - build-frontend
      - scan-backend:
          requires:
            - build-backend
      - deploy-infrastructure:
          requires:
            - build-backend
            - build-frontend
      - configure-infrastructure:
          requires:
            - deploy-infrastructure
      - run-migrations:
          requires:
            - configure-infrastructure
      - deploy-frontend:
          requires:
            - run-migrations
      - deploy-backend:
          requires:
            - run-migrations
      - smoke-test:
          requires: [deploy-backend, deploy-frontend]
